// <auto-generated />
using System;
using System.Collections.Generic;
using FaeterjAcademico.Infrastructure.Persistence.Academico;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaeterjAcademico.Infrastructure.Persistence.Academico.Migrations
{
    [DbContext(typeof(AcademicoDbContext))]
    [Migration("20260926201301_AddDocumentosPessoais")]
    partial class AddDocumentosPessoais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PeriodoAtual")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DadosPessoais", "FaeterjAcademico.Domain.Entities.Aluno.DadosPessoais#DadosPessoais", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Cpf")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("Cpf");

                            b1.Property<DateOnly?>("DataNascimento")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Naturalidade")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Naturalidade");

                            b1.Property<string>("NomeMae")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("NomeMae");

                            b1.Property<string>("NomePai")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("NomePai");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Numero");

                            b1.Property<DateOnly?>("RgDataEmissao")
                                .HasColumnType("date")
                                .HasColumnName("RgDataEmissao");

                            b1.Property<string>("RgNumero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RgNumero");

                            b1.Property<string>("RgOrgaoEmissor")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RgOrgaoEmissor");

                            b1.Property<string>("RgUf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("RgUf");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Uf");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Documentos", "FaeterjAcademico.Domain.Entities.Aluno.Documentos#DocumentosAluno", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("CertificadoReservista")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("CertificadoReservista");

                            b1.Property<int?>("EnsinoMedioAnoConclusao")
                                .HasColumnType("integer")
                                .HasColumnName("EnsinoMedioAnoConclusao");

                            b1.Property<string>("EnsinoMedioInstituicao")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("EnsinoMedioInstituicao");

                            b1.Property<string>("TituloEleitor")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("TituloEleitor");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Disponibilidade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Slot", "FaeterjAcademico.Domain.Entities.Disponibilidade.Slot#HorarioSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Dia")
                                .HasColumnType("integer")
                                .HasColumnName("Dia");

                            b1.Property<TimeOnly>("HoraFim")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraFim");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraInicio");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Disponibilidades", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.DocumentoAnexo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("Conteudo")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("DocumentosAnexos", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("CustoSolucao")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("GeradoEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Grades", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.LogSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHoraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("EntidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DataHoraUtc");

                    b.HasIndex("EntidadeTipo", "EntidadeId");

                    b.ToTable("LogsSistema", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("CargaHorariaSemanal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Periodo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.MateriaProfessor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("MateriaId", "ProfessorId")
                        .IsUnique();

                    b.ToTable("MateriaProfessores", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.MaterialComplementar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ArquivoNomeOriginal")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EnviadoPorProfessorId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.ToTable("MateriaisComplementares", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LancadaPorProfessorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.HasIndex("AlunoId", "TurmaId");

                    b.ToTable("Notas", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.PeriodoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Slot", "FaeterjAcademico.Domain.Entities.PeriodoAula.Slot#HorarioSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Dia")
                                .HasColumnType("integer")
                                .HasColumnName("Dia");

                            b1.Property<TimeOnly>("HoraFim")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraFim");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraInicio");
                        });

                    b.HasKey("Id");

                    b.ToTable("PeriodosAula", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.PreRequisito", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MateriaRequisitoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MateriaRequisitoId");

                    b.HasIndex("MateriaId", "MateriaRequisitoId")
                        .IsUnique();

                    b.ToTable("PreRequisitos", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Presenca", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAula")
                        .HasColumnType("date");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Presente")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RegistradaPorProfessorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.HasIndex("AlunoId", "TurmaId", "DataAula")
                        .IsUnique();

                    b.ToTable("Presencas", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Professor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DadosPessoais", "FaeterjAcademico.Domain.Entities.Professor.DadosPessoais#DadosPessoais", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("Cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Cidade");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Complemento");

                            b1.Property<string>("Cpf")
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("Cpf");

                            b1.Property<DateOnly?>("DataNascimento")
                                .HasColumnType("date")
                                .HasColumnName("DataNascimento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Logradouro");

                            b1.Property<string>("Naturalidade")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Naturalidade");

                            b1.Property<string>("NomeMae")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("NomeMae");

                            b1.Property<string>("NomePai")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("NomePai");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Numero");

                            b1.Property<DateOnly?>("RgDataEmissao")
                                .HasColumnType("date")
                                .HasColumnName("RgDataEmissao");

                            b1.Property<string>("RgNumero")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RgNumero");

                            b1.Property<string>("RgOrgaoEmissor")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RgOrgaoEmissor");

                            b1.Property<string>("RgUf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("RgUf");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("Uf");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Formacao", "FaeterjAcademico.Domain.Entities.Professor.Formacao#FormacaoProfessor", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("LattesUrl")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("LattesUrl");

                            b1.Property<string>("Titulacao")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Titulacao");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Professores", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnexoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("RespondidaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RespondidaPorAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resposta")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("Status");

                    b.ToTable("Solicitacoes", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PeriodoAulaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodoCurricular")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uuid");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Slot", "FaeterjAcademico.Domain.Entities.Turma.Slot#HorarioSlot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Dia")
                                .HasColumnType("integer")
                                .HasColumnName("Dia");

                            b1.Property<TimeOnly>("HoraFim")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraFim");

                            b1.Property<TimeOnly>("HoraInicio")
                                .HasColumnType("time without time zone")
                                .HasColumnName("HoraInicio");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("PeriodoAulaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas", (string)null);
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Disponibilidade", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Professor", null)
                        .WithMany("Disponibilidades")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.MateriaProfessor", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.MaterialComplementar", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Nota", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.PreRequisito", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriaRequisitoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Presenca", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Turma", null)
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Solicitacao", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Turma", b =>
                {
                    b.HasOne("FaeterjAcademico.Domain.Entities.Grade", null)
                        .WithMany("Turmas")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Materia", null)
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.PeriodoAula", null)
                        .WithMany()
                        .HasForeignKey("PeriodoAulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FaeterjAcademico.Domain.Entities.Professor", null)
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Grade", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("FaeterjAcademico.Domain.Entities.Professor", b =>
                {
                    b.Navigation("Disponibilidades");
                });
#pragma warning restore 612, 618
        }
    }
}
